version: '3.3'

services:

  bot:
    restart: unless-stopped
    build: .
    working_dir: /bot
    volumes:
      - .:/bot
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - BOT_USERS=${BOT_USERS}
      - WEBHOOK_ENABLE=${WEBHOOK_ENABLE}
      - WEBHOOK_HOST=${WEBHOOK_HOST}
      - WEBHOOK_PORT=${WEBHOOK_PORT}
      - WEBHOOK_LISTEN=${WEBHOOK_LISTEN}
    ports:
      - 88:88
    depends_on:
      - mongodb
    links:
      - mongodb
    command: python start.py

  mongodb:
    restart: unless-stopped
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodata: